---
abstract: 'the glorious sound of the vuvuzela'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101780, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Vuvuzela
resources:
  homepage: http://github.com/bingos/acme-vuvuzela/tree
  repository: git://github.com/bingos/acme-vuvuzela.git
version: 0.02
