---
abstract: 'the glorious sound of the vuvuzela'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Vuvuzela
resources:
  homepage: https://github.com/bingos/acme-vuvuzela
  repository: https://github.com/bingos/acme-vuvuzela.git
version: '0.04'
